name: UI Automation tests nightly run on dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    env:
      EMAIL_USERNAME2: ${{ secrets.EMAIL_USERNAME2 }}
      APP_PASSWORD2: ${{ secrets.APP_PASSWORD2 }}
      AES_USERNAME2: ${{ secrets.AES_USERNAME2 }}
      AES_PASSWORD: ${{ secrets.AES_PASSWORD }}
      AES_ENV: ${{ secrets.AES_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests
        run: |
          python -m pytest -k ui_tests --browser headless-chrome --html=tests_results/report.html

      - name: Generate Test Summary
        if: always()
        id: generate_summary
        run: |
          python ./utils/generate_test_report.py --file_name report.html > summary.txt
          SUMMARY=$(cat summary.txt)
          echo "SUMMARY=${SUMMARY}" >> $GITHUB_ENV

      - name: Notify Microsoft Teams
        if: always()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "UI Automation Test Results",
            "text": "UI Tests Run Summary: ${{ env.SUMMARY }}\nStatus: ${{ job.status }}\nRepository: ${{ github.repository }}\nWorkflow Run: [View Results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\nJob: ${{ github.job }}\nDuration: ${{ steps.duration.outputs.time }}\nBranch: ${{ github.ref }}\nEvent: ${{ github.event_name }}"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

  rerun-on-failure:
    runs-on: ubuntu-latest
    needs: ui-tests 
    if: failure()
    steps:
      - name: Re-run UI tests after failure
        run: echo "Re-running the failed tests"
      
      - name: Run UI tests again
        run: |
          python -m pytest -k ui_tests --browser headless-chrome --html=tests_results/report_retry.html

      - name: Generate Test Summary for Retry
        if: always()
        id: generate_summary_retry
        run: |
          python ./utils/generate_test_report.py --file_name report_retry.html > summary_retry.txt
          SUMMARY_RETRY=$(cat summary_retry.txt)
          echo "SUMMARY_RETRY=${SUMMARY_RETRY}" >> $GITHUB_ENV

      - name: Send Retry Results to Microsoft Teams
        if: always()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "UI Automation Retry Test Results",
            "text": "UI Tests Retry Run Summary: ${{ env.SUMMARY_RETRY }}\nStatus: ${{ job.status }}\nRepository: ${{ github.repository }}\nWorkflow Run: [View Results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\nJob: ${{ github.job }}\nDuration: ${{ steps.duration.outputs.time }}\nBranch: ${{ github.ref }}\nEvent: ${{ github.event_name }}"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}